#!/bin/bash

cd ~
if [ "$1" = "-p" ]; then
  srm -r go
  srm -r websites
  srm -r .Private
  srm -r setup-ubuntu
  srm -r .ssh
  srm -r .rbenv
  srm -r .pyenv
  srm -r .nodebrew
  srm .bash_history
  history -c
  exit
fi


rm -rf go
rm -rf websites
rm -rf .Private
rm -rf setup-ubuntu
rm -rf .ssh
rm -rf .rbenv
rm -rf .pyenv
rm -rf .nodebrew
rm .bash_history
