#!/bin/bash

cd ~
if [ "$1" = "-p" ]; then
  srm -r go
  srm -r websites
  rm -rf .Private
  srm -r setup-ubuntu
  srm -r .ssh
  rm -rf .rbenv
  rm -rf .pyenv
  rm -rf .nodebrew
  srm .bash_history
  history -c
  exit
fi


if [ "$1" = "-n" ]; then
  rm -rf go
  rm -rf websites
  rm -rf .Private
  rm -rf setup-ubuntu
  rm -rf .ssh
  rm -rf .rbenv
  rm -rf .pyenv
  rm -rf .nodebrew
  rm .bash_history
  history -c
  exit
fi

cd ~/setup-ubuntu
./apt-remove.sh
