#!/bin/bash

cd ~
if [ "$1" = "-p" ]; then
  srm -r Desktop/*
  srm -r Downloads/*
  srm -r Documents/*
  srm -r go
  srm -r websites
  rm -rf .Private
  srm -r .ssh
  rm -rf .rbenv
  rm -rf .pyenv
  rm -rf .nodebrew
  srm .bash_history
  cd ~/setup-ubuntu
  ./apt-remove.sh
  cd ~
  srm -r setup-ubuntu
  srm .vimrc
  history -c
  exit
fi

if [ "$1" = "-s" ]; then
  srm -sr Desktop/*
  srm -sr Downloads/*
  srm -sr Documents/*
  srm -s -r go
  srm -s -r websites
  rm -rf .Private
  srm -s -r .ssh
  rm -rf .rbenv
  rm -rf .pyenv
  rm -rf .nodebrew
  srm -s .bash_history
  cd ~/setup-ubuntu
  ./apt-remove.sh
  cd ~
  srm -s -r setup-ubuntu
  srm -s .vimrc
  history -c
  exit
fi

if [ "$1" = "-n" ]; then
  rm -rf Desktop/*
  rm -rf Downloads/*
  rm -rf Documents/*
  rm -rf go
  rm -rf websites
  rm -rf .Private
  rm -rf .ssh
  rm -rf .rbenv
  rm -rf .pyenv
  rm -rf .nodebrew
  rm .bash_history
  cd ~/setup-ubuntu
  ./apt-remove.sh
  cd ~
  rm -rf setup-ubuntu
  rm .vimrc
  history -c
  exit
fi

