#!/bin/bash

keywords="$@"

param=${keywords// /\+}
if [ "`uname`" = "Darwin" ]; then
  open "https://www.google.com/search?client=ubuntu&channel=fs&q=${param}&ie=utf-8&oe=utf-8"
  exit
fi
xdg-open "https://www.google.com/search?client=ubuntu&channel=fs&q=${param}&ie=utf-8&oe=utf-8"
